swagger: "2.0"
info:
    title: LFX V2 - Survey Service
    description: Proxy service for ITX survey system
    version: "1.0"
host: localhost:8080
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /surveys/{survey_id}:
        get:
            tags:
                - survey
            summary: get_survey survey
            description: |-
                Get survey details (proxies to ITX GET /v2/surveys/{survey_id})

                **Required security scopes for jwt**:
                  * `manage:projects`
                  * `manage:surveys`
            operationId: survey#get_survey
            parameters:
                - name: survey_id
                  in: path
                  description: Survey identifier
                  required: true
                  type: string
                - name: Authorization
                  in: header
                  description: JWT token
                  required: false
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/SurveyScheduleResult'
                        required:
                            - id
                            - survey_status
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/BadRequestError'
                        required:
                            - code
                            - message
                "401":
                    description: Unauthorized response.
                    schema:
                        $ref: '#/definitions/UnauthorizedError'
                        required:
                            - code
                            - message
                "403":
                    description: Forbidden response.
                    schema:
                        $ref: '#/definitions/ForbiddenError'
                        required:
                            - code
                            - message
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/NotFoundError'
                        required:
                            - code
                            - message
                "500":
                    description: Internal Server Error response.
                    schema:
                        $ref: '#/definitions/InternalServerError'
                        required:
                            - code
                            - message
                "503":
                    description: Service Unavailable response.
                    schema:
                        $ref: '#/definitions/ServiceUnavailableError'
                        required:
                            - code
                            - message
            schemes:
                - http
            security:
                - jwt_header_Authorization: []
        put:
            tags:
                - survey
            summary: update_survey survey
            description: |-
                Update survey (proxies to ITX PUT /v2/surveys/{survey_id}). Only allowed when status is 'disabled'

                **Required security scopes for jwt**:
                  * `manage:projects`
                  * `manage:surveys`
            operationId: survey#update_survey
            parameters:
                - name: survey_id
                  in: path
                  description: Survey identifier
                  required: true
                  type: string
                - name: Authorization
                  in: header
                  description: JWT token
                  required: false
                  type: string
                - name: update_survey_request_body
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/SurveyUpdateSurveyRequestBody'
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/SurveyScheduleResult'
                        required:
                            - id
                            - survey_status
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/BadRequestError'
                        required:
                            - code
                            - message
                "401":
                    description: Unauthorized response.
                    schema:
                        $ref: '#/definitions/UnauthorizedError'
                        required:
                            - code
                            - message
                "403":
                    description: Forbidden response.
                    schema:
                        $ref: '#/definitions/ForbiddenError'
                        required:
                            - code
                            - message
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/NotFoundError'
                        required:
                            - code
                            - message
                "500":
                    description: Internal Server Error response.
                    schema:
                        $ref: '#/definitions/InternalServerError'
                        required:
                            - code
                            - message
                "503":
                    description: Service Unavailable response.
                    schema:
                        $ref: '#/definitions/ServiceUnavailableError'
                        required:
                            - code
                            - message
            schemes:
                - http
            security:
                - jwt_header_Authorization: []
        delete:
            tags:
                - survey
            summary: delete_survey survey
            description: |-
                Delete survey (proxies to ITX DELETE /v2/surveys/{survey_id}). Only allowed when status is 'disabled'

                **Required security scopes for jwt**:
                  * `manage:projects`
                  * `manage:surveys`
            operationId: survey#delete_survey
            parameters:
                - name: survey_id
                  in: path
                  description: Survey identifier
                  required: true
                  type: string
                - name: Authorization
                  in: header
                  description: JWT token
                  required: false
                  type: string
            responses:
                "204":
                    description: No Content response.
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/BadRequestError'
                        required:
                            - code
                            - message
                "401":
                    description: Unauthorized response.
                    schema:
                        $ref: '#/definitions/UnauthorizedError'
                        required:
                            - code
                            - message
                "403":
                    description: Forbidden response.
                    schema:
                        $ref: '#/definitions/ForbiddenError'
                        required:
                            - code
                            - message
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/NotFoundError'
                        required:
                            - code
                            - message
                "500":
                    description: Internal Server Error response.
                    schema:
                        $ref: '#/definitions/InternalServerError'
                        required:
                            - code
                            - message
                "503":
                    description: Service Unavailable response.
                    schema:
                        $ref: '#/definitions/ServiceUnavailableError'
                        required:
                            - code
                            - message
            schemes:
                - http
            security:
                - jwt_header_Authorization: []
    /surveys/schedule:
        post:
            tags:
                - survey
            summary: schedule_survey survey
            description: |-
                Create a scheduled survey for ITX project committees (proxies to ITX POST /surveys/schedule)

                **Required security scopes for jwt**:
                  * `manage:projects`
                  * `manage:surveys`
            operationId: survey#schedule_survey
            parameters:
                - name: Authorization
                  in: header
                  description: JWT token
                  required: false
                  type: string
                - name: schedule_survey_request_body
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/SurveyScheduleSurveyRequestBody'
            responses:
                "201":
                    description: Created response.
                    schema:
                        $ref: '#/definitions/SurveyScheduleResult'
                        required:
                            - id
                            - survey_status
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/BadRequestError'
                        required:
                            - code
                            - message
                "401":
                    description: Unauthorized response.
                    schema:
                        $ref: '#/definitions/UnauthorizedError'
                        required:
                            - code
                            - message
                "403":
                    description: Forbidden response.
                    schema:
                        $ref: '#/definitions/ForbiddenError'
                        required:
                            - code
                            - message
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/NotFoundError'
                        required:
                            - code
                            - message
                "409":
                    description: Conflict response.
                    schema:
                        $ref: '#/definitions/ConflictError'
                        required:
                            - code
                            - message
                "500":
                    description: Internal Server Error response.
                    schema:
                        $ref: '#/definitions/InternalServerError'
                        required:
                            - code
                            - message
                "503":
                    description: Service Unavailable response.
                    schema:
                        $ref: '#/definitions/ServiceUnavailableError'
                        required:
                            - code
                            - message
            schemes:
                - http
            security:
                - jwt_header_Authorization: []
definitions:
    BadRequestError:
        title: BadRequestError
        type: object
        properties:
            code:
                type: string
                description: HTTP status code
                example: Eius consequatur sint nemo voluptatibus natus.
            message:
                type: string
                description: Error message
                example: Ipsa cum dolore aut aut earum.
        description: Bad request
        example:
            code: Nulla voluptates.
            message: Molestiae officia amet consequatur est cupiditate.
        required:
            - code
            - message
    ConflictError:
        title: ConflictError
        type: object
        properties:
            code:
                type: string
                description: HTTP status code
                example: Voluptatum sed temporibus mollitia eum omnis.
            message:
                type: string
                description: Error message
                example: Sit quaerat pariatur.
        description: Conflict
        example:
            code: Quibusdam minima ut quis dolore incidunt velit.
            message: Velit eum consectetur inventore.
        required:
            - code
            - message
    ForbiddenError:
        title: ForbiddenError
        type: object
        properties:
            code:
                type: string
                description: HTTP status code
                example: Ut provident qui voluptas explicabo.
            message:
                type: string
                description: Error message
                example: Eos eum exercitationem repellat est id rerum.
        description: Forbidden
        example:
            code: Enim veritatis quidem dolorum eos qui id.
            message: Id illo sunt error accusamus.
        required:
            - code
            - message
    InternalServerError:
        title: InternalServerError
        type: object
        properties:
            code:
                type: string
                description: HTTP status code
                example: Nihil corporis ad est.
            message:
                type: string
                description: Error message
                example: Harum molestiae ex explicabo.
        description: Internal server error
        example:
            code: Cum voluptatem eius.
            message: Occaecati modi iure.
        required:
            - code
            - message
    NotFoundError:
        title: NotFoundError
        type: object
        properties:
            code:
                type: string
                description: HTTP status code
                example: Nemo a natus eius fugiat.
            message:
                type: string
                description: Error message
                example: Sunt ipsa incidunt ullam ad nulla vitae.
        description: Not found
        example:
            code: Deleniti occaecati numquam.
            message: Temporibus voluptas quidem sint omnis et.
        required:
            - code
            - message
    ServiceUnavailableError:
        title: ServiceUnavailableError
        type: object
        properties:
            code:
                type: string
                description: HTTP status code
                example: Sit accusantium quasi illum quasi ratione minus.
            message:
                type: string
                description: Error message
                example: Libero sit rerum voluptatem dolorem est.
        description: Service unavailable
        example:
            code: Magnam reiciendis voluptas eaque culpa illo.
            message: Ad non.
        required:
            - code
            - message
    SurveyCommittee:
        title: SurveyCommittee
        type: object
        properties:
            committee_id:
                type: string
                description: Committee ID
                example: qa1e8536-a985-4cf5-b981-a170927a1d11
            committee_name:
                type: string
                description: Committee name
                example: Technical Steering Committee
            nps_value:
                type: number
                description: NPS value for this committee
                example: 0.230801757233785
                format: double
            project_id:
                type: string
                description: Project ID
                example: qa1e8536-a985-4cf5-b981-a170927a1d11
            project_name:
                type: string
                description: Project name
                example: Kubernetes
            survey_url:
                type: string
                description: Survey URL for this committee
                example: https://surveymonkey.com/r/abc123
            total_recipients:
                type: integer
                description: Total recipients for this committee
                example: 6322662353711411704
                format: int64
            total_responses:
                type: integer
                description: Total responses for this committee
                example: 8914104653003239248
                format: int64
        description: Survey committee details
        example:
            committee_id: qa1e8536-a985-4cf5-b981-a170927a1d11
            committee_name: Technical Steering Committee
            nps_value: 0.387411231464902
            project_id: qa1e8536-a985-4cf5-b981-a170927a1d11
            project_name: Kubernetes
            survey_url: https://surveymonkey.com/r/abc123
            total_recipients: 5483833992985436516
            total_responses: 230275073385347429
    SurveyScheduleResult:
        title: SurveyScheduleResult
        type: object
        properties:
            committee_category:
                type: string
                description: Committee category
                example: Possimus et aut repudiandae beatae autem repellendus.
            committee_voting_enabled:
                type: boolean
                description: Committee voting enabled
                example: false
            committees:
                type: array
                items:
                    $ref: '#/definitions/SurveyCommittee'
                description: Survey committees
                example:
                    - committee_id: qa1e8536-a985-4cf5-b981-a170927a1d11
                      committee_name: Technical Steering Committee
                      nps_value: 0.8182189272181202
                      project_id: qa1e8536-a985-4cf5-b981-a170927a1d11
                      project_name: Kubernetes
                      survey_url: https://surveymonkey.com/r/abc123
                      total_recipients: 8028691770467571286
                      total_responses: 4828934129923950055
                    - committee_id: qa1e8536-a985-4cf5-b981-a170927a1d11
                      committee_name: Technical Steering Committee
                      nps_value: 0.8182189272181202
                      project_id: qa1e8536-a985-4cf5-b981-a170927a1d11
                      project_name: Kubernetes
                      survey_url: https://surveymonkey.com/r/abc123
                      total_recipients: 8028691770467571286
                      total_responses: 4828934129923950055
                    - committee_id: qa1e8536-a985-4cf5-b981-a170927a1d11
                      committee_name: Technical Steering Committee
                      nps_value: 0.8182189272181202
                      project_id: qa1e8536-a985-4cf5-b981-a170927a1d11
                      project_name: Kubernetes
                      survey_url: https://surveymonkey.com/r/abc123
                      total_recipients: 8028691770467571286
                      total_responses: 4828934129923950055
                    - committee_id: qa1e8536-a985-4cf5-b981-a170927a1d11
                      committee_name: Technical Steering Committee
                      nps_value: 0.8182189272181202
                      project_id: qa1e8536-a985-4cf5-b981-a170927a1d11
                      project_name: Kubernetes
                      survey_url: https://surveymonkey.com/r/abc123
                      total_recipients: 8028691770467571286
                      total_responses: 4828934129923950055
            created_at:
                type: string
                description: Creation timestamp
                example: "2008-02-24T16:33:42Z"
                format: date-time
            creator_id:
                type: string
                description: Creator's user ID
                example: Id assumenda aliquid tenetur iste maxime.
            creator_name:
                type: string
                description: Creator's full name
                example: Ea placeat maxime doloremque fuga corrupti nesciunt.
            creator_username:
                type: string
                description: Creator's username
                example: Ducimus et laudantium adipisci facilis.
            email_body:
                type: string
                description: Email body HTML
                example: Non quisquam ea earum.
            email_body_text:
                type: string
                description: Email body plain text
                example: Non ea necessitatibus ut.
            email_subject:
                type: string
                description: Email subject line
                example: Laborum impedit sed minima molestiae.
            id:
                type: string
                description: Survey identifier
                example: 4e8165a9-9b29-4506-b093-ab0a4aae9b84
            is_nps_survey:
                type: boolean
                description: Whether this is an NPS survey
                example: true
            is_project_survey:
                type: boolean
                description: Whether project-level or global-level survey
                example: false
            last_modified_at:
                type: string
                description: Last modification timestamp
                example: "2000-12-25T20:59:58Z"
                format: date-time
            last_modified_by:
                type: string
                description: User ID of last modifier
                example: Omnis provident mollitia officiis hic quis voluptatem.
            latest_automated_reminder_sent_at:
                type: string
                description: Latest automated reminder sent date
                example: "1990-11-25T15:55:31Z"
                format: date-time
            next_automated_reminder_at:
                type: string
                description: Next automated reminder date
                example: "1996-10-12T08:42:02Z"
                format: date-time
            nps_value:
                type: number
                description: NPS value
                example: 0.02939836553974077
                format: double
            num_automated_reminders_sent:
                type: integer
                description: Number of automated reminders sent
                example: 9052506591129251631
                format: int64
            num_automated_reminders_to_send:
                type: integer
                description: Number of automated reminders to send
                example: 5729380638560439360
                format: int64
            num_detractors:
                type: integer
                description: Number of detractors
                example: 6019971395331458837
                format: int64
            num_passives:
                type: integer
                description: Number of passives
                example: 2012976779373182903
                format: int64
            num_promoters:
                type: integer
                description: Number of promoters
                example: 6678044145170269543
                format: int64
            response_status:
                type: string
                description: Response status
                example: scheduled
                enum:
                    - scheduled
                    - open
                    - closed
            send_immediately:
                type: boolean
                description: Whether survey is sent immediately
                example: false
            stage_filter:
                type: string
                description: Project stage filter
                example: Voluptatem deserunt fugiat.
            survey_cutoff_date:
                type: string
                description: Survey cutoff date
                example: "1987-06-09T15:17:31Z"
                format: date-time
            survey_monkey_id:
                type: string
                description: SurveyMonkey survey ID
                example: Sed laborum similique.
            survey_reminder_rate_days:
                type: integer
                description: Days between reminder emails
                example: 2462829044364668032
                format: int64
            survey_send_date:
                type: string
                description: Survey send date
                example: "1990-10-20T09:44:35Z"
                format: date-time
            survey_status:
                type: string
                description: Survey status
                example: scheduled
                enum:
                    - scheduled
                    - sending
                    - sent
                    - cancelled
            survey_title:
                type: string
                description: Survey title
                example: Omnis ad cumque voluptas.
            survey_url:
                type: string
                description: Survey URL
                example: Assumenda enim culpa.
            total_bounced_emails:
                type: integer
                description: Number of bounced emails
                example: 8878222802894390078
                format: int64
            total_recipients:
                type: integer
                description: Total number of recipients
                example: 9119374381547457991
                format: int64
            total_responses:
                type: integer
                description: Total number of responses
                example: 7405603617529075896
                format: int64
        example:
            committee_category: Enim ducimus corrupti.
            committee_voting_enabled: true
            committees:
                - committee_id: qa1e8536-a985-4cf5-b981-a170927a1d11
                  committee_name: Technical Steering Committee
                  nps_value: 0.8182189272181202
                  project_id: qa1e8536-a985-4cf5-b981-a170927a1d11
                  project_name: Kubernetes
                  survey_url: https://surveymonkey.com/r/abc123
                  total_recipients: 8028691770467571286
                  total_responses: 4828934129923950055
                - committee_id: qa1e8536-a985-4cf5-b981-a170927a1d11
                  committee_name: Technical Steering Committee
                  nps_value: 0.8182189272181202
                  project_id: qa1e8536-a985-4cf5-b981-a170927a1d11
                  project_name: Kubernetes
                  survey_url: https://surveymonkey.com/r/abc123
                  total_recipients: 8028691770467571286
                  total_responses: 4828934129923950055
                - committee_id: qa1e8536-a985-4cf5-b981-a170927a1d11
                  committee_name: Technical Steering Committee
                  nps_value: 0.8182189272181202
                  project_id: qa1e8536-a985-4cf5-b981-a170927a1d11
                  project_name: Kubernetes
                  survey_url: https://surveymonkey.com/r/abc123
                  total_recipients: 8028691770467571286
                  total_responses: 4828934129923950055
                - committee_id: qa1e8536-a985-4cf5-b981-a170927a1d11
                  committee_name: Technical Steering Committee
                  nps_value: 0.8182189272181202
                  project_id: qa1e8536-a985-4cf5-b981-a170927a1d11
                  project_name: Kubernetes
                  survey_url: https://surveymonkey.com/r/abc123
                  total_recipients: 8028691770467571286
                  total_responses: 4828934129923950055
            created_at: "1972-12-30T07:06:13Z"
            creator_id: Vel ipsam laborum quos provident ad.
            creator_name: Nisi qui repudiandae omnis molestiae assumenda.
            creator_username: In cum ipsa aliquam.
            email_body: Debitis expedita.
            email_body_text: Doloremque veniam aut molestiae.
            email_subject: Enim quidem molestiae dolores laboriosam enim odit.
            id: 4e8165a9-9b29-4506-b093-ab0a4aae9b84
            is_nps_survey: true
            is_project_survey: false
            last_modified_at: "1975-02-14T11:46:05Z"
            last_modified_by: Facilis rerum exercitationem.
            latest_automated_reminder_sent_at: "2013-08-06T04:03:36Z"
            next_automated_reminder_at: "1983-10-27T08:57:48Z"
            nps_value: 0.03313012806574674
            num_automated_reminders_sent: 9182534751931990970
            num_automated_reminders_to_send: 9205245218520049044
            num_detractors: 3278444065240458100
            num_passives: 14690644410583293
            num_promoters: 7155739197106030437
            response_status: scheduled
            send_immediately: false
            stage_filter: Nisi doloremque.
            survey_cutoff_date: "1977-09-08T09:51:25Z"
            survey_monkey_id: Autem impedit qui sequi repudiandae.
            survey_reminder_rate_days: 7448228501340993561
            survey_send_date: "2004-08-19T14:19:54Z"
            survey_status: scheduled
            survey_title: Ut iusto eius qui.
            survey_url: Ex quo nostrum et aliquid et id.
            total_bounced_emails: 8931318846366354789
            total_recipients: 359576088455319840
            total_responses: 5619996183858898427
        required:
            - id
            - survey_status
    SurveyScheduleSurveyRequestBody:
        title: SurveyScheduleSurveyRequestBody
        type: object
        properties:
            committee_voting_enabled:
                type: boolean
                description: Whether committee voting is enabled
                example: false
            committees:
                type: array
                items:
                    type: string
                    example: Tempore velit quo eos sit nemo.
                description: Array of committee IDs to send survey to
                example:
                    - Quia et iure ut exercitationem voluptatem.
                    - Nemo in impedit repellat optio.
            creator_id:
                type: string
                description: Creator's user ID
                example: Ipsam aut rerum.
            creator_name:
                type: string
                description: Creator's full name
                example: Vel ut tenetur eius optio.
            creator_username:
                type: string
                description: Creator's username
                example: Quo aut quod.
            email_body:
                type: string
                description: Email body HTML content
                example: Voluptatem et dolor ut et velit.
            email_body_text:
                type: string
                description: Email body plain text content
                example: Harum necessitatibus.
            email_subject:
                type: string
                description: Email subject line
                example: Quia et corporis nihil.
            is_project_survey:
                type: boolean
                description: Whether the survey is project-level (true) or global-level (false)
                example: false
            send_immediately:
                type: boolean
                description: Send immediately (true) or schedule for later (false)
                example: false
            stage_filter:
                type: string
                description: Project stage filter for global surveys
                example: Recusandae accusamus dolores.
            survey_cutoff_date:
                type: string
                description: Survey cutoff/end date (RFC3339 format)
                example: Eligendi quam blanditiis modi.
            survey_monkey_id:
                type: string
                description: SurveyMonkey survey ID
                example: Et et.
            survey_reminder_rate_days:
                type: integer
                description: Days between automatic reminder emails (0 = no reminders)
                example: 8172547934203773301
                format: int64
            survey_send_date:
                type: string
                description: Date to send the survey (RFC3339 format)
                example: Tempora aut.
            survey_title:
                type: string
                description: Survey title
                example: Voluptatem sunt voluptatem porro in.
        example:
            committee_voting_enabled: false
            committees:
                - Rem ut.
                - Sit corporis facilis.
                - In veniam nihil asperiores laboriosam modi est.
                - Consequatur suscipit sint fugiat.
            creator_id: Consequuntur et facilis non itaque odio occaecati.
            creator_name: Aliquam et sit vel ea porro.
            creator_username: Ut id asperiores hic autem optio.
            email_body: Quis ratione natus facilis nostrum aut neque.
            email_body_text: Natus similique sit impedit.
            email_subject: Eum non ut a qui.
            is_project_survey: false
            send_immediately: false
            stage_filter: Ut officiis omnis voluptate odit repellat earum.
            survey_cutoff_date: Voluptatem voluptatem laboriosam illo provident illum deleniti.
            survey_monkey_id: Excepturi velit expedita placeat.
            survey_reminder_rate_days: 4430846376996160925
            survey_send_date: Maiores ut quis.
            survey_title: Recusandae et distinctio et odit ratione.
    SurveyUpdateSurveyRequestBody:
        title: SurveyUpdateSurveyRequestBody
        type: object
        properties:
            committee_voting_enabled:
                type: boolean
                description: Whether committee voting is enabled
                example: false
            committees:
                type: array
                items:
                    type: string
                    example: Omnis dolor quidem quam.
                description: Array of committee IDs to send survey to
                example:
                    - In magnam incidunt nesciunt veniam.
                    - Dolorem maxime iste ab enim rerum consectetur.
                    - Natus impedit quas.
                    - Quisquam distinctio et.
            creator_id:
                type: string
                description: Creator's user ID
                example: Consequatur minima at excepturi distinctio.
            email_body:
                type: string
                description: Email body HTML content
                example: Eveniet ratione atque aliquam.
            email_body_text:
                type: string
                description: Email body plain text content
                example: Iure sed veniam.
            email_subject:
                type: string
                description: Email subject line
                example: Esse consequatur voluptas.
            survey_cutoff_date:
                type: string
                description: Survey cutoff/end date (RFC3339 format)
                example: Qui est sint.
            survey_reminder_rate_days:
                type: integer
                description: Days between automatic reminder emails (0 = no reminders)
                example: 3144401038536148794
                format: int64
            survey_send_date:
                type: string
                description: Date to send the survey (RFC3339 format)
                example: Quia rerum esse adipisci quia.
            survey_title:
                type: string
                description: Survey title
                example: Debitis ut ea qui occaecati.
        example:
            committee_voting_enabled: true
            committees:
                - Aut ducimus ea modi.
                - Ad repellendus.
            creator_id: Sunt non minus magnam et sunt.
            email_body: Est dolor saepe voluptatem et eius in.
            email_body_text: Autem corporis sit delectus voluptas.
            email_subject: Nostrum provident nihil quam quaerat dolor.
            survey_cutoff_date: Voluptate eius nihil ut ut quos.
            survey_reminder_rate_days: 2783816419315910773
            survey_send_date: Ipsam et nulla.
            survey_title: Facilis aut doloribus perspiciatis expedita ipsam aut.
    UnauthorizedError:
        title: UnauthorizedError
        type: object
        properties:
            code:
                type: string
                description: HTTP status code
                example: Culpa minus consequuntur vitae.
            message:
                type: string
                description: Error message
                example: Et in possimus nihil et aut explicabo.
        description: Unauthorized
        example:
            code: Iusto nemo impedit doloremque deleniti.
            message: Sint at quaerat.
        required:
            - code
            - message
securityDefinitions:
    jwt_header_Authorization:
        type: apiKey
        description: |-
            Heimdall JWT authorization

            **Security Scopes**:
              * `read:projects`: Read project data
              * `manage:projects`: Manage projects
              * `manage:surveys`: Manage surveys
        name: Authorization
        in: header
